name 'graylog2'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'All Rights Reserved'
description 'Installs/Configures graylog2'
version '0.4.9'
chef_version '>= 16.0'

supports 'debian'
supports 'redhat'
supports 'rocky'