name 'grafana'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'All Rights Reserved'
description 'Installs/Configures grafana'
version '0.1.0'
chef_version '>= 16.0'

supports 'rocky'
supports 'redhat'
