name 'prometheus'
maintainer 'Jeremy Eckelton'
maintainer_email 'jeremy.eckelton@gmail.com'
license 'All Rights Reserved'
description 'Installs/Configures prometheus'
version '0.1.2'
chef_version '>= 16.0'

supports 'rocky'
supports 'redhat'
