name 'rundeck'
maintainer 'Jeremy Eckelton'
maintainer_email 'jeremy.eckelton@gmail.com'
license 'All Rights Reserved'
description 'Installs/Configures rundeck'
version '0.1.18'
chef_version '>= 16.0'

supports 'rocky'
supports 'redhat'